### ISSUE TITLE
Admin menu missing

### ISSUE THREAD

**Issue by buhovac** [ec-europa/ec_europa#33]
Dear colleagues,

I am trying to implement new ec_europa theme to my Eurydice website (platform 2.4)
Steps I made are : 
- Download Atomium 7.x-2.2 The NextEuropa base theme (Enable)
- Download EC Europa theme (Enable)
- Enable : NextEuropa Formatters (nexteuropa_formatters),
NextEuropa Formatters - Views (nexteuropa_formatters_views),
NextEuropa Formatters - Fields (nexteuropa_formatters_fields)

And to check basic look I have enabled and set as default EC Europa, after I visit homepage there is no Admin menu.
![image](https://user-images.githubusercontent.com/8874230/33883757-568ee156-df3d-11e7-98c8-2a7fc0138014.png)

And still can't be sure that header is displayed properly, I have attached image.
For instructions how to I used read.me  from https://github.com/ec-europa/ec_europa#a-installation

Best regards,
Marko Buhovac

**Comment by drupol** [comment]
Hi,

It might be a stupid question, but did you cleared the cache ?

Thanks.

**Comment by buhovac** [comment]
Hi Yes :)

**Comment by drupol** [comment]
Ok I needed to be sure :-)

Now, could you do this:

1. `drush cc all`
2. `drush en admin_menu admin_menu_toolbar admin_menu_devel -y`
3. `drush en nexteuropa_ecl_migrate -y`
4. `drush eval '_nexteuropa_ecl_migrate_blocks()'`
5. `drush cc all`

Let me know if it's better.

**Comment by buhovac** [comment]
This solved my troubles, since I am using c9 for my development, this also might be helpful for other users, so it would be good to add these lines to install instructions.

Thank you very much,
Best regards,
Marko

**Comment by drupol** [comment]
Cool that's a great news.

The documentation is a good idea, but I really think that we should find the cause of this issue.

Were you able to find where it could come from ?

The function [_nexteuropa_ecl_migrate_blocks()](https://github.com/ec-europa/platform-dev/blob/master/profiles/common/modules/custom/nexteuropa_ecl_migrate/nexteuropa_ecl_migrate.module#L11) is move block around and almost nothing else.

Can you reproduce the issue and see what is going on ? Maybe some required blocks were not in their regions ?

**Comment by buhovac** [comment]
Now it is a mystery, today again I don't have admin menu... :( 
I did all those steps again, but this time no luck...

**Comment by drupol** [comment]
I think it's a cache problem related to C9.

Are you able to reproduce it locally ?

**Comment by buhovac** [comment]
I didn't try, I will try, then let you know.
