### ISSUE TITLE
Problem with admin menu

### ISSUE THREAD

**Issue by albertoperezdosaula** [ec-europa/ec_europa#46]
Hi, when we create a subtheme of ec_europa we have a problem with admin_menu, sometimes it dissapear randomly and when we clean caches it appear again.

We think that is a problem with our subtheme because if we active again the ec_europa base_theme, the admin_menu always appear at the top of the page.

Thanks a lot.

**Comment by albertoperezdosaula** [comment]
Sorry but its a problem with our subtheme. I´m clossing the issue. Thanks

**Comment by drupol** [comment]
Hey,

Hellow :-)

What was the issue ?

**Comment by albertoperezdosaula** [comment]
I think, that is the same problem like that: https://github.com/ec-europa/ec_europa/issues/33

**Comment by drupol** [comment]
Ok, great :)

Feel free to ping us again if you encounter issues.
