### ISSUE TITLE
Page headers are not same as library documentation

### ISSUE THREAD

**Issue by albertoperezdosaula** [ec-europa/ec_europa#47]
Hi.

We have download EC-Europa theme and we saw that the template page-header.tpl.php is different like https://ec-europa.github.io/europa-component-library/components/detail/ecl-page-headers--default por example the h1 title not appear on tpl

Regards

**Comment by drupol** [comment]
Hello,

We are aware of the issue and we have been explicitly asked to remove it from the header.
There is a ticket about that on our board, see [NEPT-1653](https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-1653) and don't hesitate to participate to the discussion.

I will close this ticket as it's not considered as a real issue.

Thanks.
