### ISSUE TITLE
Cross-Site Scripting Vulnerability

### ISSUE THREAD

**Issue by VictorBonasa** [ec-europa/ec_europa#80]
Hi,

There is a XSS vulnerabitily, when user input is displayed to web user without any proper validation and sanitization, allowing an attacker to inject and execute malicious scripts into the generated page.

When a new node is created, with an input like **"/><script>prompt('XSS_title')</script>** on the title field.

![xss_1](https://user-images.githubusercontent.com/6597264/46196672-040e4980-c308-11e8-815a-519234b4853c.png)

And then we edit, it shows the stored script without sanitize the output.

![xss_2](https://user-images.githubusercontent.com/6597264/46196706-17b9b000-c308-11e8-8c6c-c3a115fbe46d.png)

This sanitization is required to handle potentially dangerous characters in a safe way. The data should be encoded to sanitize potentially malicious characters disregarding their origin (database, request parameter, hardcoded, etc.) and depending on the context in which the input data is inserted.

Please let me know if you need additional information. Regards

**Comment by aritomelo** [comment]
I am not able to expose the vulnerability with atomium+ec_europa. 
I will keep it open for a second look.

**Comment by aritomelo** [comment]
The issue has been closed once it has been fixed on title module by this [patch](http://cgit.drupalcode.org/title/commit/?id=5c81d2ccca53d9d1e70252b0b04a065f414d0c0d)
